### ISSUE TITLE
Remove config.yml contents from readthedocs ?

### ISSUE THREAD

**Issue by kevinrue** [sims-lab/capture-c#29]
- "Don't Repeat Yourself": Any update to the YAML file would need to be manually copied in the docs to keep them up to date. Easy to forget.
- There are already two links to to the YAML file in this page of the docs. Users can view the latest contents of the file that way, without the need to include the contents on the file in the docs themselves.
- There is no specific comment on the contents of the YAML file, so no real point to display them at this point.
- Removing the contents will encourage users to follow the links to the file and realise that they should make a copy of that file rather than copy-paste it from the docs with the associated risks of copy-pasting glitches.

**Comment by alsmith151** [comment]
Done in a9432ae738fedf285cecb875592a724e1c15e486

**Comment by kevinrue** [comment]
I should have said: I did it in the PR: https://github.com/sims-lab/capture-c/pull/31
